### ISSUE TITLE
404 after page reload on create wallet

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp-lite#47]
Steps: 
1. Click Create new Wallet
2. on the mnemonics page try to reload (reload / Command+R)
3. you get the 404

Try the same with one and 2 steps further, on the mnemonics confirmation page and passwords setup, same issue. 

The same for the recover wallet from mnemonics and import wallet file.

<img width="1105" alt="Screenshot 2024-07-24 at 21 44 16" src="https://github.com/user-attachments/assets/72a5a73c-a704-4b08-aa5a-8dea10d0ea16">

**Comment by brusherru** [comment]
Ok, it's doable in two ways:
1. `catch-all` should be set on server-side to redirect everything to `index.html`, and then React will handle it (and basically it will redirect to the first screen)
2. `HashRouter`, which will make URLs like `wallet.spacemesh.io/#/create/set-password` which is probably good enough for us, because we don't need SEO here :)

So I'll replace current router with HashRouter and it should be super quick solution
